### PR TITLE
Add Protfolio Website. With HTML5,CSS3 & JS (Purely Front-End)

### PR DESCRIPTION
**Pull request by Bhuvan804**

### CODE REVIEW

**Comment by PrajjwalDatir** [comment]
any issues?

**Comment by Bhuvan804** [comment]
none.
works fine

**Review by PrajjwalDatir — COMMENTED** [review]
Images not related to project? can you explain your work.

**Comment by Bhuvan804** [comment]
Ive added a Portfolio Website Template.

**Pull request closed without merging**
